# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/Message.proto\x12\x0fmessage_service\"3\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06\x63oords\x18\x02 \x03(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\"4\n\x14MessageCreateRequest\x12\x0e\n\x06\x63oords\x18\x01 \x03(\x02\x12\x0c\n\x04text\x18\x02 \x01(\t\" \n\x12MessageCreateReply\x12\n\n\x02id\x18\x01 \x01(\t2m\n\x0eMessageService\x12[\n\rMessageCreate\x12%.message_service.MessageCreateRequest\x1a#.message_service.MessageCreateReplyB\x13Z\x11./message_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021./message_service'
  _globals['_MESSAGE']._serialized_start=40
  _globals['_MESSAGE']._serialized_end=91
  _globals['_MESSAGECREATEREQUEST']._serialized_start=93
  _globals['_MESSAGECREATEREQUEST']._serialized_end=145
  _globals['_MESSAGECREATEREPLY']._serialized_start=147
  _globals['_MESSAGECREATEREPLY']._serialized_end=179
  _globals['_MESSAGESERVICE']._serialized_start=181
  _globals['_MESSAGESERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
