# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AccountService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41\x63\x63ountService.proto\x12\x0f\x61\x63\x63ount_service\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0btelegram_id\x18\x02 \x01(\x03\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08\x66ullname\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"H\n\rCreateRequest\x12\x13\n\x0btelegram_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08\x66ullname\x18\x03 \x01(\t\"\x1c\n\x0e\x43reateResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x32[\n\x0e\x41\x63\x63ountService\x12I\n\x06\x43reate\x12\x1e.account_service.CreateRequest\x1a\x1f.account_service.CreateResponseB\x13Z\x11./account_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AccountService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021./account_service'
  _globals['_ACCOUNT']._serialized_start=74
  _globals['_ACCOUNT']._serialized_end=200
  _globals['_CREATEREQUEST']._serialized_start=202
  _globals['_CREATEREQUEST']._serialized_end=274
  _globals['_CREATERESPONSE']._serialized_start=276
  _globals['_CREATERESPONSE']._serialized_end=304
  _globals['_ACCOUNTSERVICE']._serialized_start=306
  _globals['_ACCOUNTSERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
